service: nodejs-serverless-express
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: src/server.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-bundle
